echo "===== Browserbite External ====="
#python3 main.py browserbite dt external 3 >> results/browserbite-dt-external.results.txt
#python3 main.py browserbite dt external 5 >> results/browserbite-dt-external.results.txt
#python3 main.py browserbite dt external 10 >> results/browserbite-dt-external.results.txt
#python3 main.py browserbite dt external 20 >> results/browserbite-dt-external.results.txt
python3 main.py browserbite dt external 300 >> results/browserbite-dt-external.results.txt
#python3 main.py browserbite randomforest external 3 >> results/browserbite-randomforest-external.results.txt
#python3 main.py browserbite randomforest external 5 >> results/browserbite-randomforest-external.results.txt
#python3 main.py browserbite randomforest external 10 >> results/browserbite-randomforest-external.results.txt
#python3 main.py browserbite randomforest external 20 >> results/browserbite-randomforest-external.results.txt
python3 main.py browserbite randomforest external 300 >> results/browserbite-randomforest-external.results.txt
#python3 main.py browserbite svm external 3 >> results/browserbite-svm-external.results.txt
#python3 main.py browserbite svm external 5 >> results/browserbite-svm-external.results.txt
#python3 main.py browserbite svm external 10 >> results/browserbite-svm-external.results.txt
#python3 main.py browserbite svm external 20 >> results/browserbite-svm-external.results.txt
python3 main.py browserbite svm external 300 >> results/browserbite-svm-external.results.txt
#python3 main.py browserbite nn external 3 >> results/browserbite-nn-external.results.txt
#python3 main.py browserbite nn external 5 >> results/browserbite-nn-external.results.txt
#python3 main.py browserbite nn external 10 >> results/browserbite-nn-external.results.txt
#python3 main.py browserbite nn external 20 >> results/browserbite-nn-external.results.txt
python3 main.py browserbite nn external 300 >> results/browserbite-nn-external.results.txt
echo "===== Browserbite Internal ====="
#python3 main.py browserbite dt internal 3 >> results/browserbite-dt-internal.results.txt
#python3 main.py browserbite dt internal 5 >> results/browserbite-dt-internal.results.txt
#python3 main.py browserbite dt internal 10 >> results/browserbite-dt-internal.results.txt
#python3 main.py browserbite dt internal 20 >> results/browserbite-dt-internal.results.txt
python3 main.py browserbite dt internal 300 >> results/browserbite-dt-internal.results.txt
#python3 main.py browserbite randomforest internal 3 >> results/browserbite-randomforest-internal.results.txt
#python3 main.py browserbite randomforest internal 5 >> results/browserbite-randomforest-internal.results.txt
#python3 main.py browserbite randomforest internal 10 >> results/browserbite-randomforest-internal.results.txt
#python3 main.py browserbite randomforest internal 20 >> results/browserbite-randomforest-internal.results.txt
python3 main.py browserbite randomforest internal 300 >> results/browserbite-randomforest-internal.results.txt
#python3 main.py browserbite svm internal 3 >> results/browserbite-svm-internal.results.txt
#python3 main.py browserbite svm internal 5 >> results/browserbite-svm-internal.results.txt
#python3 main.py browserbite svm internal 10 >> results/browserbite-svm-internal.results.txt
#python3 main.py browserbite svm internal 20 >> results/browserbite-svm-internal.results.txt
python3 main.py browserbite svm internal 300 >> results/browserbite-svm-internal.results.txt
#python3 main.py browserbite nn internal 3 >> results/browserbite-nn-internal.results.txt
#python3 main.py browserbite nn internal 5 >> results/browserbite-nn-internal.results.txt
#python3 main.py browserbite nn internal 10 >> results/browserbite-nn-internal.results.txt
#python3 main.py browserbite nn internal 20 >> results/browserbite-nn-internal.results.txt
python3 main.py browserbite nn internal 300 >> results/browserbite-nn-internal.results.txt

echo "===== CrossCheck External ====="
#python3 main.py crosscheck dt external 3 >> results/crosscheck-dt-external.results.txt
#python3 main.py crosscheck dt external 5 >> results/crosscheck-dt-external.results.txt
#python3 main.py crosscheck dt external 10 >> results/crosscheck-dt-external.results.txt
#python3 main.py crosscheck dt external 20 >> results/crosscheck-dt-external.results.txt
python3 main.py crosscheck dt external 300 >> results/crosscheck-dt-external.results.txt
#python3 main.py crosscheck randomforest external 3 >> results/crosscheck-randomforest-external.results.txt
#python3 main.py crosscheck randomforest external 5 >> results/crosscheck-randomforest-external.results.txt
#python3 main.py crosscheck randomforest external 10 >> results/crosscheck-randomforest-external.results.txt
#python3 main.py crosscheck randomforest external 20 >> results/crosscheck-randomforest-external.results.txt
python3 main.py crosscheck randomforest external 300 >> results/crosscheck-randomforest-external.results.txt
#python3 main.py crosscheck svm external 3 >> results/crosscheck-svm-external.results.txt
#python3 main.py crosscheck svm external 5 >> results/crosscheck-svm-external.results.txt
#python3 main.py crosscheck svm external 10 >> results/crosscheck-svm-external.results.txt
#python3 main.py crosscheck svm external 20 >> results/crosscheck-svm-external.results.txt
python3 main.py crosscheck svm external 300 >> results/crosscheck-svm-external.results.txt
#python3 main.py crosscheck nn external 3 >> results/crosscheck-nn-external.results.txt
#python3 main.py crosscheck nn external 5 >> results/crosscheck-nn-external.results.txt
#python3 main.py crosscheck nn external 10 >> results/crosscheck-nn-external.results.txt
#python3 main.py crosscheck nn external 20 >> results/crosscheck-nn-external.results.txt
python3 main.py crosscheck nn external 300 >> results/crosscheck-nn-external.results.txt
echo "===== CrossCheck Internal ====="
#python3 main.py crosscheck dt internal 3 >> results/crosscheck-dt-internal.results.txt
#python3 main.py crosscheck dt internal 5 >> results/crosscheck-dt-internal.results.txt
#python3 main.py crosscheck dt internal 10 >> results/crosscheck-dt-internal.results.txt
#python3 main.py crosscheck dt internal 20 >> results/crosscheck-dt-internal.results.txt
python3 main.py crosscheck dt internal 300 >> results/crosscheck-dt-internal.results.txt
#python3 main.py crosscheck randomforest internal 3 >> results/crosscheck-randomforest-internal.results.txt
#python3 main.py crosscheck randomforest internal 5 >> results/crosscheck-randomforest-internal.results.txt
#python3 main.py crosscheck randomforest internal 10 >> results/crosscheck-randomforest-internal.results.txt
#python3 main.py crosscheck randomforest internal 20 >> results/crosscheck-randomforest-internal.results.txt
python3 main.py crosscheck randomforest internal 300 >> results/crosscheck-randomforest-internal.results.txt
#python3 main.py crosscheck svm internal 3 >> results/crosscheck-svm-internal.results.txt
#python3 main.py crosscheck svm internal 5 >> results/crosscheck-svm-internal.results.txt
#python3 main.py crosscheck svm internal 10 >> results/crosscheck-svm-internal.results.txt
#python3 main.py crosscheck svm internal 20 >> results/crosscheck-svm-internal.results.txt
python3 main.py crosscheck svm internal 300 >> results/crosscheck-svm-internal.results.txt
#python3 main.py crosscheck nn internal 3 >> results/crosscheck-nn-internal.results.txt
#python3 main.py crosscheck nn internal 5 >> results/crosscheck-nn-internal.results.txt
#python3 main.py crosscheck nn internal 10 >> results/crosscheck-nn-internal.results.txt
#python3 main.py crosscheck nn internal 20 >> results/crosscheck-nn-internal.results.txt
python3 main.py crosscheck nn internal 300 >> results/crosscheck-nn-internal.results.txt

echo "===== BrowserNinja 1 External ====="
#python3 main.py browserninja1 dt external 3 >> results/browserninja1-dt-external.results.txt
#python3 main.py browserninja1 dt external 5 >> results/browserninja1-dt-external.results.txt
#python3 main.py browserninja1 dt external 10 >> results/browserninja1-dt-external.results.txt
#python3 main.py browserninja1 dt external 20 >> results/browserninja1-dt-external.results.txt
python3 main.py browserninja1 dt external 300 >> results/browserninja1-dt-external.results.txt
#python3 main.py browserninja1 randomforest external 3 >> results/browserninja1-randomforest-external.results.txt
#python3 main.py browserninja1 randomforest external 5 >> results/browserninja1-randomforest-external.results.txt
#python3 main.py browserninja1 randomforest external 10 >> results/browserninja1-randomforest-external.results.txt
#python3 main.py browserninja1 randomforest external 20 >> results/browserninja1-randomforest-external.results.txt
python3 main.py browserninja1 randomforest external 300 >> results/browserninja1-randomforest-external.results.txt
#python3 main.py browserninja1 svm external 3 >> results/browserninja1-svm-external.results.txt
#python3 main.py browserninja1 svm external 5 >> results/browserninja1-svm-external.results.txt
#python3 main.py browserninja1 svm external 10 >> results/browserninja1-svm-external.results.txt
#python3 main.py browserninja1 svm external 20 >> results/browserninja1-svm-external.results.txt
python3 main.py browserninja1 svm external 300 >> results/browserninja1-svm-external.results.txt
#python3 main.py browserninja1 nn external 3 >> results/browserninja1-nn-external.results.txt
#python3 main.py browserninja1 nn external 5 >> results/browserninja1-nn-external.results.txt
#python3 main.py browserninja1 nn external 10 >> results/browserninja1-nn-external.results.txt
#python3 main.py browserninja1 nn external 20 >> results/browserninja1-nn-external.results.txt
python3 main.py browserninja1 nn external 300 >> results/browserninja1-nn-external.results.txt
echo "===== BrowserNinja 1 Internal ====="
#python3 main.py browserninja1 dt internal 3 >> results/browserninja1-dt-internal.results.txt
#python3 main.py browserninja1 dt internal 5 >> results/browserninja1-dt-internal.results.txt
#python3 main.py browserninja1 dt internal 10 >> results/browserninja1-dt-internal.results.txt
#python3 main.py browserninja1 dt internal 20 >> results/browserninja1-dt-internal.results.txt
python3 main.py browserninja1 dt internal 300 >> results/browserninja1-dt-internal.results.txt
#python3 main.py browserninja1 randomforest internal 3 >> results/browserninja1-randomforest-internal.results.txt
#python3 main.py browserninja1 randomforest internal 5 >> results/browserninja1-randomforest-internal.results.txt
#python3 main.py browserninja1 randomforest internal 10 >> results/browserninja1-randomforest-internal.results.txt
#python3 main.py browserninja1 randomforest internal 20 >> results/browserninja1-randomforest-internal.results.txt
python3 main.py browserninja1 randomforest internal 300 >> results/browserninja1-randomforest-internal.results.txt
#python3 main.py browserninja1 svm internal 3 >> results/browserninja1-svm-internal.results.txt
#python3 main.py browserninja1 svm internal 5 >> results/browserninja1-svm-internal.results.txt
#python3 main.py browserninja1 svm internal 10 >> results/browserninja1-svm-internal.results.txt
#python3 main.py browserninja1 svm internal 20 >> results/browserninja1-svm-internal.results.txt
python3 main.py browserninja1 svm internal 300 >> results/browserninja1-svm-internal.results.txt
#python3 main.py browserninja1 nn internal 3 >> results/browserninja1-nn-internal.results.txt
#python3 main.py browserninja1 nn internal 5 >> results/browserninja1-nn-internal.results.txt
#python3 main.py browserninja1 nn internal 10 >> results/browserninja1-nn-internal.results.txt
#python3 main.py browserninja1 nn internal 20 >> results/browserninja1-nn-internal.results.txt
python3 main.py browserninja1 nn internal 300 >> results/browserninja1-nn-internal.results.txt

echo "===== BrowserNinja 2 External ====="
#python3 main.py browserninja2 dt external 3 >> results/browserninja2-dt-external.results.txt
#python3 main.py browserninja2 dt external 5 >> results/browserninja2-dt-external.results.txt
#python3 main.py browserninja2 dt external 10 >> results/browserninja2-dt-external.results.txt
#python3 main.py browserninja2 dt external 20 >> results/browserninja2-dt-external.results.txt
#python3 main.py browserninja2 dt external 30 >> results/browserninja2-dt-external.results.txt
#python3 main.py browserninja2 dt external 40 >> results/browserninja2-dt-external.results.txt
python3 main.py browserninja2 dt external 300 >> results/browserninja2-dt-external.results.txt
#python3 main.py browserninja2 randomforest external 3 >> results/browserninja2-randomforest-external.results.txt
#python3 main.py browserninja2 randomforest external 5 >> results/browserninja2-randomforest-external.results.txt
#python3 main.py browserninja2 randomforest external 10 >> results/browserninja2-randomforest-external.results.txt
#python3 main.py browserninja2 randomforest external 20 >> results/browserninja2-randomforest-external.results.txt
#python3 main.py browserninja2 randomforest external 30 >> results/browserninja2-randomforest-external.results.txt
#python3 main.py browserninja2 randomforest external 40 >> results/browserninja2-randomforest-external.results.txt
python3 main.py browserninja2 randomforest external 300 >> results/browserninja2-randomforest-external.results.txt
#python3 main.py browserninja2 svm external 3 >> results/browserninja2-svm-external.results.txt
#python3 main.py browserninja2 svm external 5 >> results/browserninja2-svm-external.results.txt
#python3 main.py browserninja2 svm external 10 >> results/browserninja2-svm-external.results.txt
#python3 main.py browserninja2 svm external 20 >> results/browserninja2-svm-external.results.txt
#python3 main.py browserninja2 svm external 30 >> results/browserninja2-svm-external.results.txt
#python3 main.py browserninja2 svm external 40 >> results/browserninja2-svm-external.results.txt
python3 main.py browserninja2 svm external 300 >> results/browserninja2-svm-external.results.txt
#python3 main.py browserninja2 nn external 3 >> results/browserninja2-nn-external.results.txt
#python3 main.py browserninja2 nn external 5 >> results/browserninja2-nn-external.results.txt
#python3 main.py browserninja2 nn external 10 >> results/browserninja2-nn-external.results.txt
#python3 main.py browserninja2 nn external 20 >> results/browserninja2-nn-external.results.txt
#python3 main.py browserninja2 nn external 30 >> results/browserninja2-nn-external.results.txt
#python3 main.py browserninja2 nn external 40 >> results/browserninja2-nn-external.results.txt
python3 main.py browserninja2 nn external 300 >> results/browserninja2-nn-external.results.txt
echo "===== BrowserNinja 2 Internal ====="
#python3 main.py browserninja2 dt internal 3 >> results/browserninja2-dt-internal.results.txt
#python3 main.py browserninja2 dt internal 5 >> results/browserninja2-dt-internal.results.txt
#python3 main.py browserninja2 dt internal 10 >> results/browserninja2-dt-internal.results.txt
#python3 main.py browserninja2 dt internal 20 >> results/browserninja2-dt-internal.results.txt
#python3 main.py browserninja2 dt internal 30 >> results/browserninja2-dt-internal.results.txt
#python3 main.py browserninja2 dt internal 40 >> results/browserninja2-dt-internal.results.txt
python3 main.py browserninja2 dt internal 300 >> results/browserninja2-dt-internal.results.txt
#python3 main.py browserninja2 randomforest internal 3 >> results/browserninja2-randomforest-internal.results.txt
#python3 main.py browserninja2 randomforest internal 5 >> results/browserninja2-randomforest-internal.results.txt
#python3 main.py browserninja2 randomforest internal 10 >> results/browserninja2-randomforest-internal.results.txt
#python3 main.py browserninja2 randomforest internal 20 >> results/browserninja2-randomforest-internal.results.txt
#python3 main.py browserninja2 randomforest internal 30 >> results/browserninja2-randomforest-internal.results.txt
#python3 main.py browserninja2 randomforest internal 40 >> results/browserninja2-randomforest-internal.results.txt
python3 main.py browserninja2 randomforest internal 300 >> results/browserninja2-randomforest-internal.results.txt
#python3 main.py browserninja2 svm internal 3 >> results/browserninja2-svm-internal.results.txt
#python3 main.py browserninja2 svm internal 5 >> results/browserninja2-svm-internal.results.txt
#python3 main.py browserninja2 svm internal 10 >> results/browserninja2-svm-internal.results.txt
#python3 main.py browserninja2 svm internal 20 >> results/browserninja2-svm-internal.results.txt
#python3 main.py browserninja2 svm internal 30 >> results/browserninja2-svm-internal.results.txt
#python3 main.py browserninja2 svm internal 40 >> results/browserninja2-svm-internal.results.txt
python3 main.py browserninja2 svm internal 300 >> results/browserninja2-svm-internal.results.txt
#python3 main.py browserninja2 nn internal 3 >> results/browserninja2-nn-internal.results.txt
#python3 main.py browserninja2 nn internal 5 >> results/browserninja2-nn-internal.results.txt
#python3 main.py browserninja2 nn internal 10 >> results/browserninja2-nn-internal.results.txt
#python3 main.py browserninja2 nn internal 20 >> results/browserninja2-nn-internal.results.txt
#python3 main.py browserninja2 nn internal 30 >> results/browserninja2-nn-internal.results.txt
#python3 main.py browserninja2 nn internal 40 >> results/browserninja2-nn-internal.results.txt
python3 main.py browserninja2 nn internal 300 >> results/browserninja2-nn-internal.results.txt

echo "===== BrowserNinja 3 External ====="
#python3 main.py all dt external 5 >> results/browserninja3-dt-external.results.txt
#python3 main.py all dt external 10 >> results/browserninja3-dt-external.results.txt
#python3 main.py all dt external 15 >> results/browserninja3-dt-external.results.txt
#python3 main.py all dt external 20 >> results/browserninja3-dt-external.results.txt
#python3 main.py all dt external 300 >> results/browserninja3-dt-external.results.txt
#python3 main.py all randomforest external 5 >> results/browserninja3-randomforest-external.results.txt
#python3 main.py all randomforest external 10 >> results/browserninja3-randomforest-external.results.txt
#python3 main.py all randomforest external 15 >> results/browserninja3-randomforest-external.results.txt
#python3 main.py all randomforest external 20 >> results/browserninja3-randomforest-external.results.txt
#python3 main.py all randomforest external 300 >> results/browserninja3-randomforest-external.results.txt
#python3 main.py all svm external 5 >> results/browserninja3-svm-external.results.txt
#python3 main.py all svm external 10 >> results/browserninja3-svm-external.results.txt
#python3 main.py all svm external 15 >> results/browserninja3-svm-external.results.txt
#python3 main.py all svm external 20 >> results/browserninja3-svm-external.results.txt
#python3 main.py all svm external 300 >> results/browserninja3-svm-external.results.txt
#python3 main.py all nn external 5 >> results/browserninja3-nn-external.results.txt
#python3 main.py all nn external 10 >> results/browserninja3-nn-external.results.txt
#python3 main.py all nn external 15 >> results/browserninja3-nn-external.results.txt
#python3 main.py all nn external 20 >> results/browserninja3-nn-external.results.txt
#python3 main.py all nn external 300 >> results/browserninja3-nn-external.results.txt

echo "===== BrowserNinja 3 Internal ====="
#python3 main.py all dt internal 5 >> results/browserninja3-dt-internal.results.txt
#python3 main.py all dt internal 10 >> results/browserninja3-dt-internal.results.txt
#python3 main.py all dt internal 15 >> results/browserninja3-dt-internal.results.txt
#python3 main.py all dt internal 20 >> results/browserninja3-dt-internal.results.txt
#python3 main.py all dt internal 300 >> results/browserninja3-dt-internal.results.txt
#python3 main.py all randomforest internal 5 >> results/browserninja3-randomforest-internal.results.txt
#python3 main.py all randomforest internal 10 >> results/browserninja3-randomforest-internal.results.txt
#python3 main.py all randomforest internal 15 >> results/browserninja3-randomforest-internal.results.txt
#python3 main.py all randomforest internal 20 >> results/browserninja3-randomforest-internal.results.txt
#python3 main.py all randomforest internal 300 >> results/browserninja3-randomforest-internal.results.txt
#python3 main.py all svm internal 5 >> results/browserninja3-svm-internal.results.txt
#python3 main.py all svm internal 10 >> results/browserninja3-svm-internal.results.txt
#python3 main.py all svm internal 15 >> results/browserninja3-svm-internal.results.txt
#python3 main.py all svm internal 20 >> results/browserninja3-svm-internal.results.txt
#python3 main.py all svm internal 300 >> results/browserninja3-svm-internal.results.txt
#python3 main.py all nn internal 5 >> results/browserninja3-nn-internal.results.txt
#python3 main.py all nn internal 10 >> results/browserninja3-nn-internal.results.txt
#python3 main.py all nn internal 15 >> results/browserninja3-nn-internal.results.txt
#python3 main.py all nn internal 20 >> results/browserninja3-nn-internal.results.txt
#python3 main.py all nn internal 300 >> results/browserninja3-nn-internal.results.txt
